apiVersion: v1
kind: Service
metadata:
  name: student-gpa-calculator-service
spec:
  selector:
    app: student-gpa-calculator
  ports:
    - protocol: TCP
      port: 80       # Port exposed to the cluster
      targetPort: 8080 # Port your Java app listens on
  type: NodePort # Allows access for testing